### ISSUE TITLE
Release 1.1.0 task list

### ISSUE THREAD

**Issue by vicentebolea** [DICL/EclipseDFS#48]
There is a few changes to be made for the next minor release:
- [ ]  #51 : |compatible| Add doxygen to document the code
- [ ]  #50 : |compatible| Change raw pointers to smart pointers (Many bugs were caused by that #46) 
- [ ]  #52 : |compatible| Remove commented code and adopt unified coding style
- [x]  #49 : |compatible| Decide open source license [Critical]
- [x]  #41 : |incompatible| Change the way the EclipseDFS initializes [Critical]
- [ ]  #55 : |incompatible| Change dfsput/dfsget... to dfs [put|get|format|ls]
- [x]  #59 : |incompatible| dfsformat [Critical]
- [ ]  #56 : |incompatible| Create dfs [show] to display blocks locations of a file. 

Note that previous _releases_ were _pre-releases_, version 1.1.0 aims to be a release.
Compatibles changes will be released in versions 1.0.*, incompatibles will wait until 
all of them are done to relase 1.1.0
